# Generated by Django 4.2.7 on 2025-05-28 07:58

from django.db import migrations, models
import trainings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('goal_type', models.CharField(choices=[('distance', 'Distancia'), ('duration', 'Duración'), ('frequency', 'Frecuencia'), ('speed', 'Velocidad'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de objetivo')),
                ('target_value', models.FloatField(help_text='Valor objetivo (km, minutos, etc.)', verbose_name='Valor objetivo')),
                ('period', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('yearly', 'Anual'), ('custom', 'Personalizado')], default='weekly', max_length=20, verbose_name='Periodo')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'db_table': 'objetivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('elevation', models.FloatField(blank=True, null=True, verbose_name='Elevación')),
                ('time', models.DateTimeField(verbose_name='Tiempo')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Ritmo cardíaco')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='Velocidad')),
                ('cadence', models.FloatField(blank=True, help_text='Cadencia en este punto (pasos/min)', null=True, verbose_name='Cadencia')),
                ('temperature', models.FloatField(blank=True, help_text='Temperatura ambiente (°C)', null=True, verbose_name='Temperatura')),
            ],
            options={
                'verbose_name': 'Punto de ruta',
                'verbose_name_plural': 'Puntos de ruta',
                'db_table': 'puntos_ruta',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='título', max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, db_column='descripción', null=True, verbose_name='Descripción')),
                ('activity_type', models.CharField(choices=[('running', 'Correr'), ('cycling', 'Ciclismo'), ('swimming', 'Natación'), ('walking', 'Caminar'), ('hiking', 'Senderismo'), ('other', 'Otro')], db_column='tipo_de_actividad', default='running', max_length=20, verbose_name='Tipo de actividad')),
                ('gpx_file', models.FileField(blank=True, db_column='archivo_gpx_tc', null=True, upload_to=trainings.models.gpx_file_path, verbose_name='Archivo GPX/TCX')),
                ('date', models.DateField(blank=True, db_column='fecha', null=True, verbose_name='Fecha')),
                ('start_time', models.TimeField(blank=True, db_column='hora_de_inicio', null=True, verbose_name='Hora de inicio')),
                ('duration', models.DurationField(blank=True, db_column='duración', null=True, verbose_name='Duración')),
                ('distance', models.FloatField(blank=True, db_column='distancia', help_text='Distancia en kilómetros', null=True, verbose_name='Distancia')),
                ('avg_speed', models.FloatField(blank=True, db_column='velocidad_promedio', help_text='Velocidad promedio en km/h', null=True, verbose_name='Velocidad promedio')),
                ('max_speed', models.FloatField(blank=True, db_column='velocidad_máxima', help_text='Velocidad máxima en km/h', null=True, verbose_name='Velocidad máxima')),
                ('avg_heart_rate', models.FloatField(blank=True, db_column='ritmo_cardíaco_promedio', help_text='Ritmo cardíaco promedio', null=True, verbose_name='Ritmo cardíaco promedio')),
                ('max_heart_rate', models.FloatField(blank=True, help_text='Ritmo cardíaco máximo', null=True, verbose_name='Ritmo cardíaco máximo')),
                ('elevation_gain', models.FloatField(blank=True, help_text='Ganancia de elevación en metros', null=True, verbose_name='Ganancia de elevación')),
                ('calories', models.IntegerField(blank=True, help_text='Calorías quemadas', null=True, verbose_name='Calorías quemadas')),
                ('avg_cadence', models.FloatField(blank=True, db_column='cadencia_promedio', help_text='Cadencia promedio (pasos/min)', null=True, verbose_name='Cadencia promedio')),
                ('max_cadence', models.FloatField(blank=True, db_column='cadencia_máxima', help_text='Cadencia máxima (pasos/min)', null=True, verbose_name='Cadencia máxima')),
                ('avg_temperature', models.FloatField(blank=True, db_column='temperatura_promedio', help_text='Temperatura promedio (°C)', null=True, verbose_name='Temperatura promedio')),
                ('min_temperature', models.FloatField(blank=True, db_column='temperatura_mínima', help_text='Temperatura mínima (°C)', null=True, verbose_name='Temperatura mínima')),
                ('max_temperature', models.FloatField(blank=True, db_column='temperatura_máxima', help_text='Temperatura máxima (°C)', null=True, verbose_name='Temperatura máxima')),
                ('file_processed', models.BooleanField(db_column='archivo_procesado', default=False, verbose_name='Archivo procesado')),
                ('processing_error', models.TextField(blank=True, db_column='error_de_procesamiento', null=True, verbose_name='Error de procesamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_de_creación', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_de_actualización', verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Entrenamiento',
                'verbose_name_plural': 'Entrenamientos',
                'db_table': 'entrenamientos',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
