# Generated by Django 5.2.1 on 2025-05-20 20:48

import django.db.models.deletion
import trainings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackpoint',
            options={'ordering': ['time'], 'verbose_name': 'Punto de ruta', 'verbose_name_plural': 'Puntos de ruta'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'Entrenamiento', 'verbose_name_plural': 'Entrenamientos'},
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('distance', 'Distancia'), ('duration', 'Duración'), ('frequency', 'Frecuencia'), ('speed', 'Velocidad'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de objetivo'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Completado'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='period',
            field=models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('yearly', 'Anual'), ('custom', 'Personalizado')], default='weekly', max_length=20, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_value',
            field=models.FloatField(help_text='Valor objetivo (km, minutos, etc.)', verbose_name='Valor objetivo'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='elevation',
            field=models.FloatField(blank=True, null=True, verbose_name='Elevación'),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ritmo cardíaco'),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='latitude',
            field=models.FloatField(verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='longitude',
            field=models.FloatField(verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocidad'),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='time',
            field=models.DateTimeField(verbose_name='Tiempo'),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_points', to='trainings.training', verbose_name='Entrenamiento'),
        ),
        migrations.AlterField(
            model_name='training',
            name='activity_type',
            field=models.CharField(choices=[('running', 'Correr'), ('cycling', 'Ciclismo'), ('swimming', 'Natación'), ('walking', 'Caminar'), ('hiking', 'Senderismo'), ('other', 'Otro')], default='running', max_length=20, verbose_name='Tipo de actividad'),
        ),
        migrations.AlterField(
            model_name='training',
            name='avg_heart_rate',
            field=models.FloatField(blank=True, help_text='Ritmo cardíaco promedio', null=True, verbose_name='Ritmo cardíaco promedio'),
        ),
        migrations.AlterField(
            model_name='training',
            name='avg_speed',
            field=models.FloatField(blank=True, help_text='Velocidad promedio en km/h', null=True, verbose_name='Velocidad promedio'),
        ),
        migrations.AlterField(
            model_name='training',
            name='calories',
            field=models.IntegerField(blank=True, help_text='Calorías quemadas', null=True, verbose_name='Calorías quemadas'),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='training',
            name='distance',
            field=models.FloatField(blank=True, help_text='Distancia en kilómetros', null=True, verbose_name='Distancia'),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='training',
            name='elevation_gain',
            field=models.FloatField(blank=True, help_text='Ganancia de elevación en metros', null=True, verbose_name='Ganancia de elevación'),
        ),
        migrations.AlterField(
            model_name='training',
            name='gpx_file',
            field=models.FileField(blank=True, null=True, upload_to=trainings.models.gpx_file_path, verbose_name='Archivo GPX/TCX'),
        ),
        migrations.AlterField(
            model_name='training',
            name='max_heart_rate',
            field=models.FloatField(blank=True, help_text='Ritmo cardíaco máximo', null=True, verbose_name='Ritmo cardíaco máximo'),
        ),
        migrations.AlterField(
            model_name='training',
            name='max_speed',
            field=models.FloatField(blank=True, help_text='Velocidad máxima en km/h', null=True, verbose_name='Velocidad máxima'),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='training',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='training',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
