# Generated by Django 4.2.7 on 2025-05-27 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trainings.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='activity_type',
            field=models.CharField(choices=[('running', 'Correr'), ('cycling', 'Ciclismo'), ('swimming', 'Natación'), ('walking', 'Caminar'), ('hiking', 'Senderismo'), ('other', 'Otro')], db_column='tipo_de_actividad', default='running', max_length=20, verbose_name='Tipo de actividad'),
        ),
        migrations.AlterField(
            model_name='training',
            name='avg_cadence',
            field=models.FloatField(blank=True, db_column='cadencia_promedio', help_text='Cadencia promedio (pasos/min)', null=True, verbose_name='Cadencia promedio'),
        ),
        migrations.AlterField(
            model_name='training',
            name='avg_heart_rate',
            field=models.FloatField(blank=True, db_column='ritmo_cardíaco_promedio', help_text='Ritmo cardíaco promedio', null=True, verbose_name='Ritmo cardíaco promedio'),
        ),
        migrations.AlterField(
            model_name='training',
            name='avg_speed',
            field=models.FloatField(blank=True, db_column='velocidad_promedio', help_text='Velocidad promedio en km/h', null=True, verbose_name='Velocidad promedio'),
        ),
        migrations.AlterField(
            model_name='training',
            name='avg_temperature',
            field=models.FloatField(blank=True, db_column='temperatura_promedio', help_text='Temperatura promedio (°C)', null=True, verbose_name='Temperatura promedio'),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_de_creación', verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(blank=True, db_column='fecha', null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, db_column='descripción', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='training',
            name='distance',
            field=models.FloatField(blank=True, db_column='distancia', help_text='Distancia en kilómetros', null=True, verbose_name='Distancia'),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.DurationField(blank=True, db_column='duración', null=True, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='training',
            name='file_processed',
            field=models.BooleanField(db_column='archivo_procesado', default=False, verbose_name='Archivo procesado'),
        ),
        migrations.AlterField(
            model_name='training',
            name='gpx_file',
            field=models.FileField(blank=True, db_column='archivo_gpx_tc', null=True, upload_to=trainings.models.gpx_file_path, verbose_name='Archivo GPX/TCX'),
        ),
        migrations.AlterField(
            model_name='training',
            name='max_cadence',
            field=models.FloatField(blank=True, db_column='cadencia_máxima', help_text='Cadencia máxima (pasos/min)', null=True, verbose_name='Cadencia máxima'),
        ),
        migrations.AlterField(
            model_name='training',
            name='max_speed',
            field=models.FloatField(blank=True, db_column='velocidad_máxima', help_text='Velocidad máxima en km/h', null=True, verbose_name='Velocidad máxima'),
        ),
        migrations.AlterField(
            model_name='training',
            name='max_temperature',
            field=models.FloatField(blank=True, db_column='temperatura_máxima', help_text='Temperatura máxima (°C)', null=True, verbose_name='Temperatura máxima'),
        ),
        migrations.AlterField(
            model_name='training',
            name='min_temperature',
            field=models.FloatField(blank=True, db_column='temperatura_mínima', help_text='Temperatura mínima (°C)', null=True, verbose_name='Temperatura mínima'),
        ),
        migrations.AlterField(
            model_name='training',
            name='processing_error',
            field=models.TextField(blank=True, db_column='error_de_procesamiento', null=True, verbose_name='Error de procesamiento'),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(blank=True, db_column='hora_de_inicio', null=True, verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(db_column='título', max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='training',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='fecha_de_actualización', verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='training',
            name='user',
            field=models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
