# Generated by Django 5.2.1 on 2025-05-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_alter_trackpoint_options_alter_training_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Objetivo', 'verbose_name_plural': 'Objetivos'},
        ),
    ]
