# Generated by Django 4.2.7 on 2025-05-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_alter_training_date_alter_training_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackpoint',
            name='cadence',
            field=models.FloatField(blank=True, help_text='Cadencia en este punto (pasos/min)', null=True, verbose_name='Cadencia'),
        ),
        migrations.AddField(
            model_name='trackpoint',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperatura ambiente (°C)', null=True, verbose_name='Temperatura'),
        ),
        migrations.AddField(
            model_name='training',
            name='avg_cadence',
            field=models.FloatField(blank=True, help_text='Cadencia promedio (pasos/min)', null=True, verbose_name='Cadencia promedio'),
        ),
        migrations.AddField(
            model_name='training',
            name='avg_temperature',
            field=models.FloatField(blank=True, help_text='Temperatura promedio (°C)', null=True, verbose_name='Temperatura promedio'),
        ),
        migrations.AddField(
            model_name='training',
            name='max_cadence',
            field=models.FloatField(blank=True, help_text='Cadencia máxima (pasos/min)', null=True, verbose_name='Cadencia máxima'),
        ),
        migrations.AddField(
            model_name='training',
            name='max_temperature',
            field=models.FloatField(blank=True, help_text='Temperatura máxima (°C)', null=True, verbose_name='Temperatura máxima'),
        ),
        migrations.AddField(
            model_name='training',
            name='min_temperature',
            field=models.FloatField(blank=True, help_text='Temperatura mínima (°C)', null=True, verbose_name='Temperatura mínima'),
        ),
    ]
