# Generated by Django 4.2.7 on 2025-05-28 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('yearly', 'Anual')], max_length=10, verbose_name='Tipo de período')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='Mes')),
                ('week', models.IntegerField(blank=True, null=True, verbose_name='Semana')),
                ('day', models.IntegerField(blank=True, null=True, verbose_name='Día')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('training_count', models.IntegerField(default=0, verbose_name='Número de entrenamientos')),
                ('total_distance', models.FloatField(default=0, help_text='Distancia total en kilómetros', verbose_name='Distancia total')),
                ('total_duration', models.DurationField(default=datetime.timedelta(0), verbose_name='Duración total')),
                ('total_calories', models.FloatField(default=0, verbose_name='Calorías totales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Resumen de actividad',
                'verbose_name_plural': 'Resúmenes de actividad',
                'db_table': 'resumenes_actividad',
                'ordering': ['-year', '-month', '-week', '-day'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trainings', models.IntegerField(db_column='total_entrenamientos', default=0, verbose_name='Total de entrenamientos')),
                ('total_distance', models.FloatField(db_column='distancia_total', default=0, help_text='Distancia total en kilómetros', verbose_name='Distancia total')),
                ('total_duration', models.DurationField(db_column='duracion_total', default=datetime.timedelta(0), verbose_name='Duración total')),
                ('total_calories', models.IntegerField(db_column='calorías_total', default=0, verbose_name='Total de calorías')),
                ('avg_distance_per_training', models.FloatField(db_column='distancia_promedio_por_entrenamiento', default=0, help_text='Distancia promedio por entrenamiento en km', verbose_name='Distancia promedio')),
                ('avg_duration_per_training', models.DurationField(db_column='duracion_promedio_por_entrenamiento', default=datetime.timedelta(0), verbose_name='Duración promedio')),
                ('avg_speed', models.FloatField(db_column='velocidad_promedio', default=0, help_text='Velocidad promedio en km/h', verbose_name='Velocidad promedio')),
                ('avg_heart_rate', models.FloatField(db_column='ritmo_cardíaco_promedio', default=0, help_text='Ritmo cardíaco promedio', verbose_name='Ritmo cardíaco promedio')),
                ('longest_distance', models.FloatField(db_column='distancia_más_larga', default=0, help_text='Distancia más larga en km', verbose_name='Distancia más larga')),
                ('longest_duration', models.DurationField(db_column='duracion_más_larga', default=datetime.timedelta(0), verbose_name='Duración más larga')),
                ('highest_speed', models.FloatField(db_column='velocidad_más_alta', default=0, help_text='Velocidad más alta en km/h', verbose_name='Velocidad más alta')),
                ('highest_elevation_gain', models.FloatField(db_column='mayor_desnivel', default=0, help_text='Mayor ganancia de elevación en metros', verbose_name='Mayor desnivel')),
                ('first_training_date', models.DateField(blank=True, db_column='fecha_del_primer_entrenamiento', null=True, verbose_name='Fecha del primer entrenamiento')),
                ('last_training_date', models.DateField(blank=True, db_column='fecha_del_último_entrenamiento', null=True, verbose_name='Fecha del último entrenamiento')),
                ('last_updated', models.DateTimeField(auto_now=True, db_column='última_actualización', verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Estadísticas de usuario',
                'verbose_name_plural': 'Estadísticas de usuarios',
                'db_table': 'estadisticas_usuario',
            },
        ),
    ]
