# Generated by Django 5.2.1 on 2025-05-20 20:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
        ('users', '0002_alter_user_options_alter_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitysummary',
            options={'ordering': ['-year', '-month', '-week', '-day'], 'verbose_name': 'Resumen de actividad', 'verbose_name_plural': 'Resúmenes de actividad'},
        ),
        migrations.AlterModelOptions(
            name='userstats',
            options={'verbose_name': 'Estadísticas de usuario', 'verbose_name_plural': 'Estadísticas de usuarios'},
        ),
        migrations.AlterField(
            model_name='activitysummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='activitysummary',
            name='day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='activitysummary',
            name='end_date',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='activitysummary',
            name='month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='activitysummary',
            name='period_type',
            field=models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('yearly', 'Anual')], max_length=10, verbose_name='Tipo de período'),
        ),
        migrations.AlterField(
            model_name='activitysummary',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='activitysummary',
            name='total_calories',
            field=models.FloatField(default=0, verbose_name='Calorías totales'),
        ),
        migrations.AlterField(
            model_name='activitysummary',
            name='total_distance',
            field=models.FloatField(default=0, help_text='Distancia total en kilómetros', verbose_name='Distancia total'),
        ),
        migrations.AlterField(
            model_name='activitysummary',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Duración total'),
        ),
        migrations.AlterField(
            model_name='activitysummary',
            name='training_count',
            field=models.IntegerField(default=0, verbose_name='Número de entrenamientos'),
        ),
        migrations.AlterField(
            model_name='activitysummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='activitysummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_summaries', to='users.user', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='activitysummary',
            name='week',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semana'),
        ),
        migrations.AlterField(
            model_name='activitysummary',
            name='year',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='avg_distance_per_training',
            field=models.FloatField(default=0, help_text='Distancia promedio por entrenamiento en km', verbose_name='Distancia promedio'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='avg_duration_per_training',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Duración promedio'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='avg_heart_rate',
            field=models.FloatField(default=0, help_text='Ritmo cardíaco promedio', verbose_name='Ritmo cardíaco promedio'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='avg_speed',
            field=models.FloatField(default=0, help_text='Velocidad promedio en km/h', verbose_name='Velocidad promedio'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='first_training_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del primer entrenamiento'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='highest_elevation_gain',
            field=models.FloatField(default=0, help_text='Mayor ganancia de elevación en metros', verbose_name='Mayor desnivel'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='highest_speed',
            field=models.FloatField(default=0, help_text='Velocidad más alta en km/h', verbose_name='Velocidad más alta'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='last_training_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del último entrenamiento'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='longest_distance',
            field=models.FloatField(default=0, help_text='Distancia más larga en km', verbose_name='Distancia más larga'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='longest_duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Duración más larga'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_calories',
            field=models.IntegerField(default=0, verbose_name='Total de calorías'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_distance',
            field=models.FloatField(default=0, help_text='Distancia total en kilómetros', verbose_name='Distancia total'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Duración total'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_trainings',
            field=models.IntegerField(default=0, verbose_name='Total de entrenamientos'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='users.user', verbose_name='Usuario'),
        ),
    ]
