# Generated by Django 4.2.7 on 2025-05-27 19:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='avg_distance_per_training',
            field=models.FloatField(db_column='distancia_promedio_por_entrenamiento', default=0, help_text='Distancia promedio por entrenamiento en km', verbose_name='Distancia promedio'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='avg_duration_per_training',
            field=models.DurationField(db_column='duracion_promedio_por_entrenamiento', default=datetime.timedelta(0), verbose_name='Duración promedio'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='avg_heart_rate',
            field=models.FloatField(db_column='ritmo_cardíaco_promedio', default=0, help_text='Ritmo cardíaco promedio', verbose_name='Ritmo cardíaco promedio'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='avg_speed',
            field=models.FloatField(db_column='velocidad_promedio', default=0, help_text='Velocidad promedio en km/h', verbose_name='Velocidad promedio'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='first_training_date',
            field=models.DateField(blank=True, db_column='fecha_del_primer_entrenamiento', null=True, verbose_name='Fecha del primer entrenamiento'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='highest_elevation_gain',
            field=models.FloatField(db_column='mayor_desnivel', default=0, help_text='Mayor ganancia de elevación en metros', verbose_name='Mayor desnivel'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='highest_speed',
            field=models.FloatField(db_column='velocidad_más_alta', default=0, help_text='Velocidad más alta en km/h', verbose_name='Velocidad más alta'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='last_training_date',
            field=models.DateField(blank=True, db_column='fecha_del_último_entrenamiento', null=True, verbose_name='Fecha del último entrenamiento'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_column='última_actualización', verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='longest_distance',
            field=models.FloatField(db_column='distancia_más_larga', default=0, help_text='Distancia más larga en km', verbose_name='Distancia más larga'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='longest_duration',
            field=models.DurationField(db_column='duracion_más_larga', default=datetime.timedelta(0), verbose_name='Duración más larga'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_calories',
            field=models.IntegerField(db_column='calorías_total', default=0, verbose_name='Total de calorías'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_distance',
            field=models.FloatField(db_column='distancia_total', default=0, help_text='Distancia total en kilómetros', verbose_name='Distancia total'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_duration',
            field=models.DurationField(db_column='duracion_total', default=datetime.timedelta(0), verbose_name='Duración total'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_trainings',
            field=models.IntegerField(db_column='total_entrenamientos', default=0, verbose_name='Total de entrenamientos'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='user',
            field=models.OneToOneField(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
